> df <- read.table("data/household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE)
> df$datetime <- as.POSIXct(paste(df$Date, df$Time), format = "%d/%m/%Y %H:%M:%S")
> sub <- df[df$datetime >= as.POSIXct("2007-02-01 00:00:00") & df$datetime < as.POSIXct("2007-02-03 00:00:00"),]
> sub$Global_active_power <- as.numeric(sub$Global_active_power)
> sub$Global_reactive_power <- as.numeric(sub$Global_reactive_power)
> sub$Voltage <- as.numeric(sub$Voltage)
> sub$Sub_metering_1 <- as.numeric(sub$Sub_metering_1)
> sub$Sub_metering_2 <- as.numeric(sub$Sub_metering_2)
> sub$Sub_metering_3 <- as.numeric(sub$Sub_metering_3)
> png("plot4.png", width = 480, height = 480)
> par(mfrow=c(2,2), mar=c(4,4,2,1))
> plot(sub$datetime, sub$Global_active_power, type="l", xlab="", ylab="Global Active Power ")
> plot(sub$datetime, sub$Voltage, type="l", xlab="datetime", ylab="Voltage")
> plot(sub$datetime, sub$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
> lines(sub$datetime, sub$Sub_metering_2, col = "red")
> lines(sub$datetime, sub$Sub_metering_3, col = "blue")
> legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1, bty="n")
> plot(sub$datetime, sub$Global_reactive_power, type="l", xlab="datetime", ylab="Global Reactive Power")
> dev.off()